[tool.ruff]
line-length = 88
target-version = "py311"

[tool.ruff.lint]
extend-select = ["E", "F", "B", "I"]
fix = true
unsafe-fixes = true

[tool.ruff.lint.isort]
known-first-party = ["calc"]

[tool.black]
line-length = 88
target-version = ["py311"]
